all:
	./jemdoc  -o ../  index.jemdoc
	./jemdoc  -o ../  awards.jemdoc
	./jemdoc  -o ../  activities.jemdoc
	./jemdoc  -o ../  letter.jemdoc
	./jemdoc  -o ../  member.jemdoc
	chmod a+r ../img/committee/*.jpg  ../doc/newsletter/*.pdf ../img/activities/*.jpg ../*.html

